### ISSUE TITLE
Build the login page

### ISSUE THREAD

**Issue by sebinbenjamin** [Quarantine-Help/quarantine-hybrid-app#1]
Build the onboarding pages for the app.

**Tasks**
- [x] Build the basic layout with the input fields.
- [x] Add validations for the input fields and show errors.
- [x] Call the login API and show the loading animation.
- [x] Handle incorrect login credentials + other login errors. 
- [x] Implement basic navigation.

**Additional context**
Please go through the discussions on https://xd.adobe.com/spec/b3bd4031-5959-47e0-4b38-da9e6454d57e-c58c/screen/69655c60-71d2-47a3-8fa0-ab86d5e9e6bf/Landing-Page - p12 
![image](https://user-images.githubusercontent.com/4099066/78961384-62df9080-7b45-11ea-8ed9-31526edf0458.png)
