### ISSUE TITLE
Add the search filtering options for the map.

### ISSUE THREAD

**Issue by sebinbenjamin** [Quarantine-Help/quarantine-hybrid-app#11]
Add filters to narrow down the map results.

**Tasks**
- [x] Create a component to Implement the basic UI/layout.
- [x] Add the component to the maps page.
- [x] Map UI to correct API params.

**Additional context**
![image](https://user-images.githubusercontent.com/4099066/79287671-aad12f80-7f18-11ea-8487-d8cb218217cd.png)

https://xd.adobe.com/view/b3bd4031-5959-47e0-4b38-da9e6454d57e-c58c/screen/6b746b46-27a9-4fe6-ab02-3def4208df3d/Volunteer-Home-Expand-Filter/ - p2

![image](https://user-images.githubusercontent.com/4099066/78962312-147fc100-7b48-11ea-841f-55cc414e9d3a.png)
