### ISSUE TITLE
User registration page for volunteers and quarantined 

### ISSUE THREAD

**Issue by sebinbenjamin** [Quarantine-Help/quarantine-hybrid-app#12]
Build the basic registration page collecting a subset of the following inputs, depending on the type of user.  
- First Name
- Last Name
- Address - [for quarantined]
- City - [for quarantined]
- Country - [for quarantined]
- Email
- Phone No
- Password
- Find my address (Geolocation API) - [for quarantined]

**Tasks**
- [x] Build a basic form with the input fields
- [ ] Use the geolocation API to get the location
- [ ] Use the Reverse Geocode API to get the address - https://developer.here.com/documentation/examples/rest/geocoder/reverse-geocode
- [ ] Auto-fill address, city and country from the Reverse geocode API response.
- [ ] Call API to save the data to the backend.
- [ ] Use loading animation for network requests.

**Additional context**

Please go through the discussion at https://xd.adobe.com/spec/b3bd4031-5959-47e0-4b38-da9e6454d57e-c58c/screen/51e62209-26ae-4679-a842-81273f794129/-Registered-Quarantined-create-basic-information - p9

![image](https://user-images.githubusercontent.com/4099066/78961501-ce296280-7b45-11ea-858e-cafe6fcd23e4.png)

Please go through the discussion at https://xd.adobe.com/spec/b3bd4031-5959-47e0-4b38-da9e6454d57e-c58c/screen/e3f5c390-4d5a-4f96-ac04-667599434baf/-Registered-Quarantined-create-basic-information-3 - p13

![image](https://user-images.githubusercontent.com/4099066/78961564-00d35b00-7b46-11ea-817a-5c1af8a17c0a.png)

**Comment by nimishawilson** [comment]
I'm working on this. Is it okay?
