### ISSUE TITLE
Page to view/edit the profile for Quarantined users

### ISSUE THREAD

**Issue by sebinbenjamin** [Quarantine-Help/quarantine-hybrid-app#13]
Add options to edit and view the profile for the Quarantined users.

**Tasks**
- [x] Build a UI similar to #12 
- [x] Add an edit button, to make the fields editable.
- [ ] Add a save button, which becomes active when the inputs are dirty.
- [ ] Warn users on exit without save, when dirty.
- [ ] Show loading animations and confirmation on Save.

**Additional context**
Go through the discussions if any, on the XD links - https://xd.adobe.com/spec/b3bd4031-5959-47e0-4b38-da9e6454d57e-c58c/screen/155638ce-564e-4a47-b526-b21bd0c6400a/-Registered-Quarantined-create-basic-information-2 - p10

![image](https://user-images.githubusercontent.com/4099066/78961907-11380580-7b47-11ea-8e77-36f0c175fd71.png)

https://xd.adobe.com/spec/b3bd4031-5959-47e0-4b38-da9e6454d57e-c58c/screen/c4b82e09-4602-42b9-b5e8-d82390871311/-Registered-Quarantined-create-basic-information-1  - p11

![image](https://user-images.githubusercontent.com/4099066/78961920-214fe500-7b47-11ea-837a-67cad9e8032b.png)
