### ISSUE TITLE
Add searchbar, toolbar to the map page and adjust map controls  

### ISSUE THREAD

**Issue by sebinbenjamin** [Quarantine-Help/quarantine-hybrid-app#8]
Complete the basic UI elements on the map page.

**Tasks**
- [x] Add a search bar and the toolbar
- [x] Fix the map div height issue
- [x] Adjust HERE maps UI controls
- [x] Add fab to get GPS and recenter the map. 

**Additional context**
Please go through the discussions on XD.

https://xd.adobe.com/view/b3bd4031-5959-47e0-4b38-da9e6454d57e-c58c/screen/0d76506f-f75f-438a-b3ba-69ec800370a1/Volunteer-Home
![image](https://user-images.githubusercontent.com/4099066/78463740-9f218400-7734-11ea-97a9-e1eebd93b2d7.png)
