### ISSUE TITLE
Create markers on the map with request locations and other data

### ISSUE THREAD

**Issue by sebinbenjamin** [Quarantine-Help/quarantine-hybrid-app#9]
Show the help request locations as markers on the map.

**Tasks**
- [x] Get nearby requests from the database
- [x] Verify API call params, with the filter component.
- [x] Show loading animations for network requests.
- [x] Set map zoom level based on the view bounds  
- [x]  Load requests as markers to the map

**Additional context**
https://xd.adobe.com/view/b3bd4031-5959-47e0-4b38-da9e6454d57e-c58c/screen/0d76506f-f75f-438a-b3ba-69ec800370a1/Volunteer-Home - p1

![image](https://user-images.githubusercontent.com/4099066/78464316-f5de8c00-773b-11ea-887e-0c4e67d9f097.png)
